export default [
  "Actuarial Science",
  "Aerospace Engineering",
  "Africana Studies",
  "American Indian and Indigenous Studies",
  "American Sign Language",
  "American Studies",
  "Animal Science",
  "Anthropology",
  "Applied Economics",
  "Applied Exercise Science",
  "Applied Mathematics",
  "Arabic",
  "Archaeology",
  "Architecture",
  "Artificial Intelligence",
  "Asian American Studies",
  "Astrobiology",
  "Astronomy",
  "Atmospheric Sciences",
  "Biological Engineering",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biometry and Statistics",
  "Business",
  "China and Asia-Pacific Studies",
  "Civil Infrastructure",
  "Classical Civilization",
  "Classics",
  "Climate Change",
  "Cognitive Science",
  "Communication",
  "Community Food Systems",
  "Comparative Literature",
  "Computer Science",
  "Creative Writing",
  "Crime, Prisons, Education, and Justice",
  "Crop Management",
  "Dance",
  "Data Science",
  "Data Science in Astronomy",
  "Demography",
  "Design & Environmental Analysis",
  "Digital Agriculture",
  "Dyson Business Minor for Engineers",
  "Dyson Business Minor for Life Sciences",
  "Earth and Atmospheric Sciences",
  "East Asian Studies",
  "English",
  "Education",
  "Electrical and Computer Engineering",
  "Engineering Communications",
  "Engineering Management",
  "Entrepreneurship",
  "Entomology",
  "Environmental Engineering",
  "Environment & Sustainability",
  "European Studies",
  "Fashion Studies",
  "Feminist, Gender, & Sexuality Studies",
  "Fiber Science",
  "Film",
  "Fine Arts",
  "Food and Agricultural Business",
  "Food Science",
  "French",
  "Fungal Biology",
  "Game Design",
  "German Studies",
  "Gerontology",
  "Global Asia Studies",
  "Global Health",
  "Health Policy",
  "Healthy Futures",
  "History",
  "History of Art",
  "History of Capitalism",
  "Horticulture",
  "Human Development",
  "Inequality Studies",
  "Infectious Disease Biology",
  "Information Science",
  "International Relations",
  "International Development Studies",
  "International Trade and Development",
  "Italian Studies",
  "Jewish Studies",
  "Landscape Studies",
  "Latin American Studies",
  "Latina/o Studies",
  "Law and Society",
  "Leadership",
  "Lesbian, Gay, Bisexual, & Transgender Studies",
  "Linguistics",
  "Marine Biology",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medieval Studies",
  "Migration Studies",
  "Minority, Indigenous, and Third World Studies",
  "Moral Psychology",
  "Music",
  "Near Eastern Studies",
  "Nutrition & Health",
  "Operations Research & Management Science",
  "Performing and Media Arts",
  "Philosophy",
  "Physics",
  "Plant Breeding",
  "Plant Sciences",
  "Policy Analysis and Management",
  "Portuguese and Brazilian Studies",
  "Psychology",
  "Public History",
  "Public Policy",
  "Public Service Studies",
  "Real Estate",
  "Religious Studies",
  "Robotics",
  "Russian",
  "Sanskrit Studies",
  "Science Communication and Public Engagement",
  "Science & Technology Studies",
  "Smart Cities",
  "Soil Science",
  "South Asian Studies",
  "Southeast Asian Studies",
  "Spanish",
  "Sustainable Agricultural and Food Systems",
  "Sustainable Business and Economic Policy",
  "Sustainable Energy Systems",
  "Theatre",
  "Urban and Regional Studies",
  "Viking Studies",
  "Visual Studies",
  "Viticulture and Enology"
]
